### ISSUE TITLE
Different Username files

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#17]
Ran into an interesting (but required) use case in my latest project using the `email` as the username.

The issue is that the user facing website is using `email` as the login, but the admin uses `username`.

We added the ability to customize the `username` field, but now it seems I'm going to need to check for both.

I see 2 potential solutions.

1. (my preferred choice) Change the `AUDIT_USERNAME_FIELD` to be a list of possible field names, in order of priority. We can then check for each.
2. Keep the `AUDIT_USERNAME_FIELD` as is, but fall back to `username` if a keyerror is raised and the custom username field is not available.

I'll be happy to make these changes (I need to anyway for this project), but would like some feedback as to your preferred solution. Maybe you have other ideas other than the two I mentioned above?

**Comment by peppelinux** [comment]
I think that `AUDIT_USERNAME_FIELD` is more polite as a list of allowed values.
I've just enabled/invited you as collaborator in this repository, we should implement a GH action CI because this project still doesn't have any unit test (warning).

I'd add a pypi token secret to enable a CD.
I can do this latter and the configuration of GH Action CI, but I need that you:

- implement this feature shown in this issue
- introduce some unit tests

**Comment by andrewebdev** [comment]
Regarding introduction to unit tests. We already have those from the previous work I did ;)
I will also add some more tests for the changes that I'll make regarding this feature.

I'll be able to work on this feature a bit later this week.

**Comment by peppelinux** [comment]
Great, I'll add a gh actions CI and a pypi CD
Your are now a formal contributors, you have the power now but I'll do my part of the work
thank you @andrewebdev

**Comment by peppelinux** [comment]
Done, CI, codecov and fancy things are ready, the most important: if you tag a new release the python package will be uploaded in pypi.
you drive @andrewebdev, do a good job!

**Comment by peppelinux** [comment]
merged:
https://github.com/peppelinux/django-audit-wazuh/commit/260eac93162601f58ef0d794bca7354f805093b5

feel free to update a new version in setup.py and then tag a new release, automatically a new pypi package will be deployed.
The new release would be 0.7.0 because this release introduce a brand new feature
